Retrieving logs...
============= i-92d39d36 ==============
-------------------------------------
/var/log/eb-version-deployment.log
-------------------------------------
2016-01-09 16:47:58,503 [INFO] Found the latest version manifest file <Key: elasticbeanstalk-ap-southeast-1-361398130125,resources/environments/e-zcae5pz8sz/_runtime/versions/manifest_1452357885352> from bucket elasticbeanstalk-ap-southeast-1-361398130125 and prefix resources/environments/e-zcae5pz8sz/_runtime/versions/
2016-01-09 16:47:58,557 [INFO] Downloaded the manifest file to /tmp/version_file_manifest
2016-01-09 16:48:00,017 [INFO] Downloaded version label app-e742-160109_221225 from s3 key <Key: elasticbeanstalk-ap-southeast-1-361398130125,resources/environments/e-zcae5pz8sz/_runtime/_versions/RTIFeed/app-e742-160109_221225>
2016-01-09 17:03:03,124 [INFO] Version manifest file name already known. The latest version manifest file key is resources/environments/e-zcae5pz8sz/_runtime/versions/manifest_1452358978083
2016-01-09 17:03:03,181 [INFO] Downloaded the manifest file to /tmp/version_file_manifest
2016-01-09 17:03:04,417 [INFO] Downloaded version label app-e742-160109_223147 from s3 key <Key: elasticbeanstalk-ap-southeast-1-361398130125,resources/environments/e-zcae5pz8sz/_runtime/_versions/RTIFeed/app-e742-160109_223147>
2016-01-09 17:19:45,395 [INFO] Version manifest file name already known. The latest version manifest file key is resources/environments/e-zcae5pz8sz/_runtime/versions/manifest_1452359981209
2016-01-09 17:19:45,449 [INFO] Downloaded the manifest file to /tmp/version_file_manifest
2016-01-09 17:19:46,985 [INFO] Downloaded version label app-c048-160109_224743 from s3 key <Key: elasticbeanstalk-ap-southeast-1-361398130125,resources/environments/e-zcae5pz8sz/_runtime/_versions/RTIFeed/app-c048-160109_224743>



-------------------------------------
/var/log/httpd/error_log
-------------------------------------
[Sat Jan 09 16:51:33.504786 2016] [:error] [pid 2841] [client 127.0.0.1:50531] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:51:38.509911 2016] [:error] [pid 2874] [client 127.0.0.1:50532] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:51:43.512880 2016] [:error] [pid 2844] [client 127.0.0.1:50533] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:51:48.517532 2016] [:error] [pid 2843] [client 127.0.0.1:50534] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:51:53.521088 2016] [:error] [pid 2866] [client 127.0.0.1:50535] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:51:58.525482 2016] [:error] [pid 2887] [client 127.0.0.1:50536] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:03.530977 2016] [:error] [pid 2842] [client 127.0.0.1:50537] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:08.536921 2016] [:error] [pid 2843] [client 127.0.0.1:50538] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:13.540208 2016] [:error] [pid 2866] [client 127.0.0.1:50539] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:18.544947 2016] [:error] [pid 2887] [client 127.0.0.1:50540] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:23.549621 2016] [:error] [pid 2874] [client 127.0.0.1:50541] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:28.554525 2016] [:error] [pid 2845] [client 127.0.0.1:50542] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:33.558477 2016] [:error] [pid 2866] [client 127.0.0.1:50543] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:38.563049 2016] [:error] [pid 2887] [client 127.0.0.1:50544] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:43.567134 2016] [:error] [pid 2874] [client 127.0.0.1:50545] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:48.571634 2016] [:error] [pid 2841] [client 127.0.0.1:50546] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:53.575889 2016] [:error] [pid 2843] [client 127.0.0.1:50547] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:52:58.580429 2016] [:error] [pid 2844] [client 127.0.0.1:50548] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:03.586455 2016] [:error] [pid 2842] [client 127.0.0.1:50549] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:08.592423 2016] [:error] [pid 2841] [client 127.0.0.1:50550] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:13.596726 2016] [:error] [pid 2843] [client 127.0.0.1:50551] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:18.601925 2016] [:error] [pid 2844] [client 127.0.0.1:50552] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:23.604661 2016] [:error] [pid 2887] [client 127.0.0.1:50553] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:28.609030 2016] [:error] [pid 2845] [client 127.0.0.1:50554] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:33.613146 2016] [:error] [pid 2843] [client 127.0.0.1:50555] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 16:53:38.618745 2016] [:error] [pid 2844] [client 127.0.0.1:50556] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:08.446731 2016] [mpm_prefork:notice] [pid 2837] AH00169: caught SIGTERM, shutting down
[Sat Jan 09 17:03:09.497557 2016] [suexec:notice] [pid 3222] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sat Jan 09 17:03:09.507190 2016] [so:warn] [pid 3222] AH01574: module wsgi_module is already loaded, skipping
[Sat Jan 09 17:03:09.509985 2016] [auth_digest:notice] [pid 3222] AH01757: generating secret for digest authentication ...
[Sat Jan 09 17:03:09.510582 2016] [lbmethod_heartbeat:notice] [pid 3222] AH02282: No slotmem from mod_heartmonitor
[Sat Jan 09 17:03:09.510616 2016] [:warn] [pid 3222] mod_wsgi: Compiled for Python/2.7.9.
[Sat Jan 09 17:03:09.510619 2016] [:warn] [pid 3222] mod_wsgi: Runtime using Python/2.7.10.
[Sat Jan 09 17:03:09.512383 2016] [mpm_prefork:notice] [pid 3222] AH00163: Apache/2.4.16 (Amazon) mod_wsgi/3.5 Python/2.7.10 configured -- resuming normal operations
[Sat Jan 09 17:03:09.512395 2016] [core:notice] [pid 3222] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sat Jan 09 17:03:12.096945 2016] [:error] [pid 3226] [client 127.0.0.1:50617] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:17.103081 2016] [:error] [pid 3229] [client 127.0.0.1:50618] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:22.109260 2016] [:error] [pid 3227] [client 127.0.0.1:50619] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:27.115348 2016] [:error] [pid 3226] [client 127.0.0.1:50620] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:32.121327 2016] [:error] [pid 3229] [client 127.0.0.1:50621] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:37.127292 2016] [:error] [pid 3227] [client 127.0.0.1:50622] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:42.133296 2016] [:error] [pid 3226] [client 127.0.0.1:50623] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:47.139441 2016] [:error] [pid 3229] [client 127.0.0.1:50624] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:52.145516 2016] [:error] [pid 3227] [client 127.0.0.1:50625] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:03:57.146542 2016] [:error] [pid 3226] [client 127.0.0.1:50626] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:02.149802 2016] [:error] [pid 3229] [client 127.0.0.1:50627] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:07.155420 2016] [:error] [pid 3227] [client 127.0.0.1:50628] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:12.161553 2016] [:error] [pid 3226] [client 127.0.0.1:50629] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:17.167482 2016] [:error] [pid 3229] [client 127.0.0.1:50630] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:22.173826 2016] [:error] [pid 3251] [client 127.0.0.1:50631] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:27.179871 2016] [:error] [pid 3228] [client 127.0.0.1:50632] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:32.186121 2016] [:error] [pid 3230] [client 127.0.0.1:50633] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:37.192182 2016] [:error] [pid 3251] [client 127.0.0.1:50634] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:42.198366 2016] [:error] [pid 3229] [client 127.0.0.1:50635] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:47.202808 2016] [:error] [pid 3261] [client 127.0.0.1:50636] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:52.206760 2016] [:error] [pid 3228] [client 127.0.0.1:50637] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:04:57.212769 2016] [:error] [pid 3229] [client 127.0.0.1:50638] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:02.218221 2016] [:error] [pid 3261] [client 127.0.0.1:50639] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:07.224280 2016] [:error] [pid 3251] [client 127.0.0.1:50640] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:12.230423 2016] [:error] [pid 3264] [client 127.0.0.1:50641] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:17.236520 2016] [:error] [pid 3230] [client 127.0.0.1:50642] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:22.242650 2016] [:error] [pid 3226] [client 127.0.0.1:50643] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:27.248644 2016] [:error] [pid 3228] [client 127.0.0.1:50644] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:32.254751 2016] [:error] [pid 3229] [client 127.0.0.1:50645] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:37.260772 2016] [:error] [pid 3261] [client 127.0.0.1:50646] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:42.265975 2016] [:error] [pid 3228] [client 127.0.0.1:50647] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:47.271962 2016] [:error] [pid 3229] [client 127.0.0.1:50648] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:52.278072 2016] [:error] [pid 3261] [client 127.0.0.1:50649] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:05:57.281854 2016] [:error] [pid 3228] [client 127.0.0.1:50650] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:02.287879 2016] [:error] [pid 3229] [client 127.0.0.1:50651] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:07.291562 2016] [:error] [pid 3230] [client 127.0.0.1:50652] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:12.297501 2016] [:error] [pid 3251] [client 127.0.0.1:50653] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:17.303507 2016] [:error] [pid 3264] [client 127.0.0.1:50654] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:22.309507 2016] [:error] [pid 3226] [client 127.0.0.1:50655] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:27.315494 2016] [:error] [pid 3261] [client 127.0.0.1:50656] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:32.320119 2016] [:error] [pid 3228] [client 127.0.0.1:50657] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:37.325736 2016] [:error] [pid 3229] [client 127.0.0.1:50658] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:42.331734 2016] [:error] [pid 3261] [client 127.0.0.1:50659] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:47.337711 2016] [:error] [pid 3228] [client 127.0.0.1:50660] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:52.343692 2016] [:error] [pid 3229] [client 127.0.0.1:50661] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:06:57.346819 2016] [:error] [pid 3261] [client 127.0.0.1:50662] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:02.352826 2016] [:error] [pid 3228] [client 127.0.0.1:50663] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:07.358805 2016] [:error] [pid 3264] [client 127.0.0.1:50664] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:12.363063 2016] [:error] [pid 3230] [client 127.0.0.1:50665] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:17.366649 2016] [:error] [pid 3251] [client 127.0.0.1:50666] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:22.371638 2016] [:error] [pid 3226] [client 127.0.0.1:50667] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:27.375319 2016] [:error] [pid 3229] [client 127.0.0.1:50668] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:32.380181 2016] [:error] [pid 3261] [client 127.0.0.1:50669] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:37.383831 2016] [:error] [pid 3228] [client 127.0.0.1:50670] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:42.388695 2016] [:error] [pid 3229] [client 127.0.0.1:50671] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:47.392443 2016] [:error] [pid 3261] [client 127.0.0.1:50672] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:52.397479 2016] [:error] [pid 3228] [client 127.0.0.1:50673] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:07:57.401055 2016] [:error] [pid 3229] [client 127.0.0.1:50674] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:08:02.406998 2016] [:error] [pid 3261] [client 127.0.0.1:50675] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:08:07.412921 2016] [:error] [pid 3251] [client 127.0.0.1:50676] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:08:12.417702 2016] [:error] [pid 3264] [client 127.0.0.1:50677] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:11:54.639596 2016] [:error] [pid 3228] [client 172.31.1.237:62257] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
[Sat Jan 09 17:11:56.416973 2016] [:error] [pid 3228] [client 172.31.1.237:62257] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py, referer: http://rtifeed-dev.elasticbeanstalk.com/
[Sat Jan 09 17:11:56.417364 2016] [:error] [pid 3226] [client 172.31.1.237:62270] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py, referer: http://rtifeed-dev.elasticbeanstalk.com/
[Sat Jan 09 17:11:56.421787 2016] [:error] [pid 3226] [client 172.31.1.237:62270] Target WSGI script not found or unable to stat: /opt/python/current/app/application.py, referer: http://rtifeed-dev.elasticbeanstalk.com/



-------------------------------------
/opt/python/log/supervisord.log
-------------------------------------
2016-01-09 16:48:07,152 CRIT Supervisor running as root (no user in config file)
2016-01-09 16:48:07,201 INFO RPC interface 'supervisor' initialized
2016-01-09 16:48:07,201 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-01-09 16:48:07,201 INFO supervisord started with pid 2628
2016-01-09 16:48:08,203 INFO spawned: 'httpd' with pid 2709
2016-01-09 16:48:10,005 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-09 16:48:34,685 INFO stopped: httpd (exit status 0)
2016-01-09 16:48:35,689 INFO spawned: 'httpd' with pid 2837
2016-01-09 16:48:36,721 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-09 17:03:08,458 INFO stopped: httpd (exit status 0)
2016-01-09 17:03:09,462 INFO spawned: 'httpd' with pid 3222
2016-01-09 17:03:10,497 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)



-------------------------------------
/var/log/httpd/access_log
-------------------------------------
127.0.0.1 (-) - - [09/Jan/2016:16:51:13 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:18 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:23 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:28 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:33 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:38 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:43 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:48 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:53 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:51:58 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:03 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:08 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:13 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:18 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:23 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:28 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:33 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:38 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:43 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:48 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:53 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:52:58 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:03 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:08 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:13 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:18 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:23 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:28 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:33 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:16:53:38 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:12 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:17 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:22 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:27 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:32 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:37 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:42 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:47 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:52 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:03:57 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:02 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:07 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:12 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:17 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:22 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:27 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:32 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:37 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:42 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:47 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:52 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:04:57 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:02 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:07 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:12 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:17 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:22 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:27 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:32 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:37 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:42 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:47 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:52 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:05:57 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:02 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:07 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:12 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:17 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:22 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:27 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:32 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:37 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:42 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:47 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:52 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:06:57 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:02 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:07 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:12 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:17 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:22 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:27 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:32 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:37 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:42 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:47 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:52 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:07:57 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:08:02 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:08:07 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
127.0.0.1 (-) - - [09/Jan/2016:17:08:12 +0000] "GET / HTTP/1.1" 404 198 "-" "Python-urllib/2.7"
172.31.1.237 (103.37.201.95) - - [09/Jan/2016:17:11:54 +0000] "GET / HTTP/1.1" 404 198 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
172.31.1.237 (103.37.201.95) - - [09/Jan/2016:17:11:56 +0000] "GET /favicon.ico HTTP/1.1" 404 209 "http://rtifeed-dev.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
172.31.1.237 (103.37.201.95) - - [09/Jan/2016:17:11:56 +0000] "GET /favicon.ico HTTP/1.1" 404 209 "http://rtifeed-dev.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
172.31.1.237 (103.37.201.95) - - [09/Jan/2016:17:11:56 +0000] "GET /favicon.ico HTTP/1.1" 404 209 "http://rtifeed-dev.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
::1 (-) - - [09/Jan/2016:17:12:56 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.16 (Amazon) mod_wsgi/3.5 Python/2.7.10 (internal dummy connection)"
::1 (-) - - [09/Jan/2016:17:12:57 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.16 (Amazon) mod_wsgi/3.5 Python/2.7.10 (internal dummy connection)"
::1 (-) - - [09/Jan/2016:17:12:58 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.16 (Amazon) mod_wsgi/3.5 Python/2.7.10 (internal dummy connection)"
::1 (-) - - [09/Jan/2016:17:13:01 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.16 (Amazon) mod_wsgi/3.5 Python/2.7.10 (internal dummy connection)"
::1 (-) - - [09/Jan/2016:17:13:02 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.16 (Amazon) mod_wsgi/3.5 Python/2.7.10 (internal dummy connection)"



-------------------------------------
/var/log/eb-activity.log
-------------------------------------
      src/lxml/lxml.etree.c:228101: error: ‘struct __pyx_vtabstruct_4lxml_5etree__BaseParser’ has no member named ‘_parseDocFromFile’
      src/lxml/lxml.etree.c:228101: error: expected expression before ‘)’ token
      src/lxml/lxml.etree.c:228101: error: expected ‘;’ before ‘__pyx_f_4lxml_5etree_11_BaseParser__parseDocFromFile’
      src/lxml/lxml.etree.c:228102: error: ‘struct __pyx_vtabstruct_4lxml_5etree__BaseParser’ has no member named ‘_parseDocFromFilelike’
      src/lxml/lxml.etree.c:228102: error: expected expression before ‘)’ token
      src/lxml/lxml.etree.c:228102: error: expected ‘;’ before ‘__pyx_f_4lxml_5etree_11_BaseParser__parseDocFromFilelike’
      src/lxml/lxml.etree.c:228200: error: ‘struct __pyx_vtabstruct_4lxml_5etree__FilelikeWriter’ has no member named ‘_createOutputBuffer’
      src/lxml/lxml.etree.c:228200: error: ‘xmlOutputBuffer’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:228200: error: expected expression before ‘)’ token
      src/lxml/lxml.etree.c:228200: error: expected ‘;’ before ‘__pyx_f_4lxml_5etree_15_FilelikeWriter__createOutputBuffer’
      src/lxml/lxml.etree.c:228201: error: ‘struct __pyx_vtabstruct_4lxml_5etree__FilelikeWriter’ has no member named ‘write’
      src/lxml/lxml.etree.c:228202: error: ‘struct __pyx_vtabstruct_4lxml_5etree__FilelikeWriter’ has no member named ‘close’
      src/lxml/lxml.etree.c:228282: error: expected declaration specifiers or ‘...’ before ‘xmlXPathContext’
      src/lxml/lxml.etree.c:228297: error: ‘struct __pyx_vtabstruct_4lxml_5etree__BaseContext’ has no member named ‘_find_cached_function’
      src/lxml/lxml.etree.c:228297: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
      src/lxml/lxml.etree.c:228297: error: expected ‘;’ before ‘__pyx_f_4lxml_5etree_12_BaseContext__find_cached_function’
      src/lxml/lxml.etree.c:228298: error: ‘struct __pyx_vtabstruct_4lxml_5etree__BaseContext’ has no member named ‘_release_temp_refs’
      src/lxml/lxml.etree.c:228299: error: ‘struct __pyx_vtabstruct_4lxml_5etree__BaseContext’ has no member named ‘_hold’
      src/lxml/lxml.etree.c:228300: error: ‘struct __pyx_vtabstruct_4lxml_5etree__BaseContext’ has no member named ‘_findDocumentForNode’
      src/lxml/lxml.etree.c:228300: error: expected declaration specifiers or ‘...’ before ‘xmlNode’
      src/lxml/lxml.etree.c:228312: error: expected declaration specifiers or ‘...’ before ‘xmlXPathContext’
      src/lxml/lxml.etree.c:228324: error: expected declaration specifiers or ‘...’ before ‘xmlXPathContext’
      src/lxml/lxml.etree.c:228330: error: expected declaration specifiers or ‘...’ before ‘xmlXPathObject’
      src/lxml/lxml.etree.c:228408: error: expected declaration specifiers or ‘...’ before ‘xsltSecurityOption’
      src/lxml/lxml.etree.c:228409: error: expected declaration specifiers or ‘...’ before ‘xsltTransformContext’
      src/lxml/lxml.etree.c:228410: error: expected declaration specifiers or ‘...’ before ‘xsltSecurityOption’
      src/lxml/lxml.etree.c:228419: error: expected declaration specifiers or ‘...’ before ‘xsltTransformContext’
      src/lxml/lxml.etree.c:228430: error: ‘struct __pyx_vtabstruct_4lxml_5etree_XSLT’ has no member named ‘_run_transform’
      src/lxml/lxml.etree.c:228430: error: expected expression before ‘)’ token
      src/lxml/lxml.etree.c:228430: error: expected ‘;’ before ‘__pyx_f_4lxml_5etree_4XSLT__run_transform’
      src/lxml/lxml.etree.c:228448: error: expected declaration specifiers or ‘...’ before ‘xmlChar’
      src/lxml/lxml.etree.c:228464: error: expected declaration specifiers or ‘...’ before ‘xmlNode’
      src/lxml/lxml.etree.c:230192: error: ‘xmlParserVersion’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:230355: error: ‘LIBXML_VERSION’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231435: error: ‘__pyx_v_4lxml_5etree___DEFAULT_ENTITY_LOADER’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231445: error: ‘xmlExternalEntityLoader’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231445: error: expected ‘)’ before ‘__pyx_f_4lxml_5etree__local_resolver’
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_NOENT’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_NOCDATA’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_NONET’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_COMPACT’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231530: error: ‘HTML_PARSE_RECOVER’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231530: error: ‘HTML_PARSE_NONET’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231530: error: ‘HTML_PARSE_COMPACT’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232227: error: ‘XML_XPATH_NUMBER_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232238: error: ‘XML_XPATH_UNFINISHED_LITERAL_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232249: error: ‘XML_XPATH_VARIABLE_REF_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232260: error: ‘XML_XPATH_INVALID_PREDICATE_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232271: error: ‘XML_XPATH_UNCLOSED_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232282: error: ‘XML_XPATH_INVALID_CHAR_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232326: error: ‘XML_XPATH_UNDEF_VARIABLE_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232337: error: ‘XML_XPATH_UNDEF_PREFIX_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232348: error: ‘XML_XPATH_UNKNOWN_FUNC_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232359: error: ‘XML_XPATH_INVALID_OPERAND’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232370: error: ‘XML_XPATH_INVALID_TYPE’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232381: error: ‘XML_XPATH_INVALID_ARITY’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232392: error: ‘XML_XPATH_INVALID_CTXT_SIZE’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232403: error: ‘XML_XPATH_INVALID_CTXT_POSITION’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232651: error: ‘LIBXSLT_VERSION’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232664: error: ‘xsltLibxsltVersion’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232677: error: ‘__pyx_v_4lxml_5etree_XSLT_DOC_DEFAULT_LOADER’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232677: error: ‘xsltDocDefaultLoader’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232687: error: ‘xsltDocLoaderFunc’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232687: error: expected ‘)’ before ‘__pyx_f_4lxml_5etree__xslt_doc_loader’
      src/lxml/lxml.etree.c: At top level:
      src/lxml/lxml.etree.c:237283: error: expected ‘)’ before ‘value’
      src/lxml/lxml.etree.c:237739: error: expected ‘)’ before ‘value’
      src/lxml/lxml.etree.c:237975: error: expected ‘)’ before ‘value’
      Compile failed: command 'gcc' failed with exit status 1
      creating tmp
      cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit3kqCOA.c -o tmp/xmlXPathInit3kqCOA.o
      /tmp/xmlXPathInit3kqCOA.c:1:26: error: libxml/xpath.h: No such file or directory
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      error: command 'gcc' failed with exit status 1
      
      ----------------------------------------
  Command "/opt/python/run/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ld_Xs3/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BeWnzI-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/python/run/venv/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-Ld_Xs3/lxml
  2016-01-09 17:20:58,357 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)


[2016-01-09T17:20:58.377Z] INFO  [25677] - [Application update/AppDeployStage0/AppDeployPreHook/03deploy.py] : Activity failed.
[2016-01-09T17:20:58.377Z] INFO  [25677] - [Application update/AppDeployStage0/AppDeployPreHook] : Activity failed.
[2016-01-09T17:20:58.377Z] INFO  [25677] - [Application update/AppDeployStage0] : Activity failed.
[2016-01-09T17:20:58.393Z] INFO  [25677] - [Application update] : Completed activity. Result:
  Application update - Command CMD-AppDeploy failed
[2016-01-09T17:21:59.842Z] INFO  [10388] - [CMD-TailLogs - stage ] : Starting activity...
[2016-01-09T17:22:00.087Z] INFO  [10388] - [CMD-TailLogs - stage /AddonsBefore] : Starting activity...
[2016-01-09T17:22:00.087Z] INFO  [10388] - [CMD-TailLogs - stage /AddonsBefore] : Completed activity.
[2016-01-09T17:22:00.087Z] INFO  [10388] - [CMD-TailLogs - stage /TailLogs] : Starting activity...
[2016-01-09T17:22:00.087Z] INFO  [10388] - [CMD-TailLogs - stage /TailLogs/TailLogs] : Starting activity...



-------------------------------------
/var/log/eb-commandprocessor.log
-------------------------------------
      src/lxml/lxml.etree.c:228312: error: expected declaration specifiers or ‘...’ before ‘xmlXPathContext’
      src/lxml/lxml.etree.c:228324: error: expected declaration specifiers or ‘...’ before ‘xmlXPathContext’
      src/lxml/lxml.etree.c:228330: error: expected declaration specifiers or ‘...’ before ‘xmlXPathObject’
      src/lxml/lxml.etree.c:228408: error: expected declaration specifiers or ‘...’ before ‘xsltSecurityOption’
      src/lxml/lxml.etree.c:228409: error: expected declaration specifiers or ‘...’ before ‘xsltTransformContext’
      src/lxml/lxml.etree.c:228410: error: expected declaration specifiers or ‘...’ before ‘xsltSecurityOption’
      src/lxml/lxml.etree.c:228419: error: expected declaration specifiers or ‘...’ before ‘xsltTransformContext’
      src/lxml/lxml.etree.c:228430: error: ‘struct __pyx_vtabstruct_4lxml_5etree_XSLT’ has no member named ‘_run_transform’
      src/lxml/lxml.etree.c:228430: error: expected expression before ‘)’ token
      src/lxml/lxml.etree.c:228430: error: expected ‘;’ before ‘__pyx_f_4lxml_5etree_4XSLT__run_transform’
      src/lxml/lxml.etree.c:228448: error: expected declaration specifiers or ‘...’ before ‘xmlChar’
      src/lxml/lxml.etree.c:228464: error: expected declaration specifiers or ‘...’ before ‘xmlNode’
      src/lxml/lxml.etree.c:230192: error: ‘xmlParserVersion’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:230355: error: ‘LIBXML_VERSION’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231435: error: ‘__pyx_v_4lxml_5etree___DEFAULT_ENTITY_LOADER’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231445: error: ‘xmlExternalEntityLoader’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231445: error: expected ‘)’ before ‘__pyx_f_4lxml_5etree__local_resolver’
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_NOENT’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_NOCDATA’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_NONET’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231455: error: ‘XML_PARSE_COMPACT’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231530: error: ‘HTML_PARSE_RECOVER’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231530: error: ‘HTML_PARSE_NONET’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:231530: error: ‘HTML_PARSE_COMPACT’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232227: error: ‘XML_XPATH_NUMBER_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232238: error: ‘XML_XPATH_UNFINISHED_LITERAL_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232249: error: ‘XML_XPATH_VARIABLE_REF_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232260: error: ‘XML_XPATH_INVALID_PREDICATE_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232271: error: ‘XML_XPATH_UNCLOSED_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232282: error: ‘XML_XPATH_INVALID_CHAR_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232326: error: ‘XML_XPATH_UNDEF_VARIABLE_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232337: error: ‘XML_XPATH_UNDEF_PREFIX_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232348: error: ‘XML_XPATH_UNKNOWN_FUNC_ERROR’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232359: error: ‘XML_XPATH_INVALID_OPERAND’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232370: error: ‘XML_XPATH_INVALID_TYPE’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232381: error: ‘XML_XPATH_INVALID_ARITY’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232392: error: ‘XML_XPATH_INVALID_CTXT_SIZE’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232403: error: ‘XML_XPATH_INVALID_CTXT_POSITION’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232651: error: ‘LIBXSLT_VERSION’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232664: error: ‘xsltLibxsltVersion’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232677: error: ‘__pyx_v_4lxml_5etree_XSLT_DOC_DEFAULT_LOADER’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232677: error: ‘xsltDocDefaultLoader’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232687: error: ‘xsltDocLoaderFunc’ undeclared (first use in this function)
      src/lxml/lxml.etree.c:232687: error: expected ‘)’ before ‘__pyx_f_4lxml_5etree__xslt_doc_loader’
      src/lxml/lxml.etree.c: At top level:
      src/lxml/lxml.etree.c:237283: error: expected ‘)’ before ‘value’
      src/lxml/lxml.etree.c:237739: error: expected ‘)’ before ‘value’
      src/lxml/lxml.etree.c:237975: error: expected ‘)’ before ‘value’
      Compile failed: command 'gcc' failed with exit status 1
      creating tmp
      cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit3kqCOA.c -o tmp/xmlXPathInit3kqCOA.o
      /tmp/xmlXPathInit3kqCOA.c:1:26: error: libxml/xpath.h: No such file or directory
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      error: command 'gcc' failed with exit status 1
      
      ----------------------------------------
  Command "/opt/python/run/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ld_Xs3/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BeWnzI-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/python/run/venv/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-Ld_Xs3/lxml
  2016-01-09 17:20:58,357 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)


[2016-01-09T17:20:58.393Z] ERROR [25677] : Command CMD-AppDeploy failed!
[2016-01-09T17:20:58.394Z] INFO  [25677] : Command processor returning results: 
{"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"(TRUNCATED)...)\n  File \"/usr/lib64/python2.7/subprocess.py\", line 540, in check_call\n    raise CalledProcessError(retcode, cmd)\nCalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1. \nHook /opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py failed. For more detail, check /var/log/eb-activity.log using console or EB CLI","returncode":1,"events":[{"msg":"Your requirements.txt is invalid. Snapshot your logs for details.","severity":"ERROR","timestamp":1452360058},{"msg":"Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1","severity":"SYSTEM","timestamp":1452360058}]}],"truncated":"true"}
[2016-01-09T17:21:59.840Z] DEBUG [10388] : Reading config file: /etc/elasticbeanstalk/.aws-eb-stack.properties
[2016-01-09T17:21:59.840Z] DEBUG [10388] : Checking if the command processor should execute...
[2016-01-09T17:21:59.842Z] DEBUG [10388] : Checking whether the command is applicable to instance (i-92d39d36)..
[2016-01-09T17:21:59.842Z] INFO  [10388] : Command is applicable to this instance (i-92d39d36)..
[2016-01-09T17:21:59.842Z] DEBUG [10388] : Checking if the received command stage is valid..
[2016-01-09T17:21:59.842Z] INFO  [10388] : No stage_num in command. Valid stage..
[2016-01-09T17:21:59.842Z] INFO  [10388] : Received command CMD-TailLogs: {"execution_data":"{\"aws_access_key_id\":\"ASIAIU3Y2EHENBOAF36A\",\"signature\":\"r38Lo77Vfmy5up5WZJ11MataMzw=\",\"security_token\":\"AQoDYXdzEMP\\\/\\\/\\\/\\\/\\\/\\\/\\\/\\\/\\\/\\\/wEawAKfxiW+J9iPTfb60tEzB4WYttM8WjG4Qpl8fm\\\/HBbHeDu8SmJMnWobAwppnSvYYCwg0Uzpgrkya7hawqqCstXwlyxWLI9sroAgu0b9htoabbzcSJIsEI2iXiefloU5gwQBRLmQe6oVfMQfvFHXw1CXO\\\/Is8tvsqSGeG6uJ+SF7iEGkZkB0qnB3waBE\\\/bZumySVUDjMiDqqXWiK+CPfFmqtH2HKAijt+40Hzg5xqCN5CMgbZmVIqW\\\/Tl0hO1y7u6Vv3+QIrIRP93vnND6RijT6cmAM3z2uT62UYF4PUuGt8KzOSl6mMNaLJ\\\/eApI5aaIhdmVicmQRW9V1z4oYgOnn4uKwi\\\/2vf\\\/+4zJxi9FeNqGxJGShRCVliasx\\\/VUxL6BLUSoiDZNhDP\\\/z5ov+z\\\/Dtff6gxFjvjrxDN8ANfH2IAm\\\/C\\\/CC1g8W0BQ==\",\"policy\":\"eyJleHBpcmF0aW9uIjoiMjAxNi0wMS0wOVQxNzo1MTo1Ny42NDdaIiwiY29uZGl0aW9ucyI6W1sic3RhcnRzLXdpdGgiLCIkeC1hbXotbWV0YS10aW1lX3N0YW1wIiwiIl0sWyJzdGFydHMtd2l0aCIsIiR4LWFtei1tZXRhLXB1Ymxpc2hfbWVjaGFuaXNtIiwiIl0sWyJzdGFydHMtd2l0aCIsIiRrZXkiLCJyZXNvdXJjZXNcL2Vudmlyb25tZW50c1wvbG9nc1wvIl0sWyJzdGFydHMtd2l0aCIsIiR4LWFtei1tZXRhLWJhdGNoX2lkIiwiIl0sWyJzdGFydHMtd2l0aCIsIiR4LWFtei1tZXRhLWZpbGVfbmFtZSIsIiJdLFsic3RhcnRzLXdpdGgiLCIkeC1hbXotc2VjdXJpdHktdG9rZW4iLCIiXSxbInN0YXJ0cy13aXRoIiwiJENvbnRlbnQtVHlwZSIsIiJdLFsiZXEiLCIkYnVja2V0IiwiZWxhc3RpY2JlYW5zdGFsay1hcC1zb3V0aGVhc3QtMS0zNjEzOTgxMzAxMjUiXSxbImVxIiwiJGFjbCIsInByaXZhdGUiXV19\"}","instance_ids":["i-92d39d36"],"data":"7c5d24f6-b6f5-11e5-bc87-95042267b0f4","command_name":"CMD-TailLogs","api_version":"1.0","resource_name":"AWSEBAutoScalingGroup","request_id":"7c5d24f6-b6f5-11e5-bc87-95042267b0f4","command_timeout":"600"}
[2016-01-09T17:21:59.842Z] INFO  [10388] : Command processor should execute command.
[2016-01-09T17:21:59.842Z] DEBUG [10388] : Storing current stage..
[2016-01-09T17:21:59.842Z] DEBUG [10388] : Stage_num does not exist. Not saving null stage. Returning..
[2016-01-09T17:21:59.842Z] INFO  [10388] : Executing CMD-TailLogs - stage 
[2016-01-09T17:21:59.842Z] INFO  [10388] : Executing command: CMD-TailLogs...
[2016-01-09T17:21:59.842Z] DEBUG [10388] : Reading config file: /etc/elasticbeanstalk/.aws-eb-stack.properties
[2016-01-09T17:21:59.843Z] DEBUG [10388] : Refreshing metadata..
[2016-01-09T17:22:00.084Z] DEBUG [10388] : Refreshed environment metadata.
[2016-01-09T17:22:00.084Z] DEBUG [10388] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_ContainerConfigFileContent||commands..
[2016-01-09T17:22:00.085Z] DEBUG [10388] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_API||_Commands..
[2016-01-09T17:22:00.085Z] INFO  [10388] : Found enabled addons: ["logpublish"].
[2016-01-09T17:22:00.086Z] INFO  [10388] : Updating Command definition of addon logpublish.
[2016-01-09T17:22:00.086Z] DEBUG [10388] : Loaded definition of Command CMD-TailLogs.
[2016-01-09T17:22:00.086Z] INFO  [10388] : Executing command CMD-TailLogs activities...
[2016-01-09T17:22:00.086Z] DEBUG [10388] : Setting environment variables..
[2016-01-09T17:22:00.087Z] INFO  [10388] : Running AddonsBefore for command CMD-TailLogs...
[2016-01-09T17:22:00.087Z] DEBUG [10388] : Running stages of Command CMD-TailLogs from stage 0 to stage 0...
[2016-01-09T17:22:00.087Z] INFO  [10388] : Running stage 0 of command CMD-TailLogs...
[2016-01-09T17:22:00.087Z] DEBUG [10388] : Loaded 1 actions for stage 0.
[2016-01-09T17:22:00.087Z] INFO  [10388] : Running 1 of 1 actions: TailLogs...



